weights: ../MIDS-W207-Spring24-Soccer-Detection/analysis/Batch/Size16/train/exp2/weights/epoch_002.pt
cfg: ''
data: data/soccertrack_square_oversampled.yaml
hyp: data/hyp.scratch.custom.yaml
epochs: 5
batch_size: 16
img_size:
- 800
- 800
rect: false
resume: true
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: true
sync_bn: false
local_rank: -1
workers: 8
project: ../MIDS-W207-Spring24-Soccer-Detection/analysis/Batch/Size16/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
v5_metric: false
world_size: 1
global_rank: -1
save_dir: ..\MIDS-W207-Spring24-Soccer-Detection\analysis\Batch\Size16\train\exp2
total_batch_size: 16
